-- CREATE TABLES CODE --
CREATE TABLE GOAL_OF(
	match_id INT UNSIGNED NOT NULL, -- USING UNSIGNED INT, SET FOREIGN KEY
    club_id INT UNSIGNED NOT NULL, -- USING UNSIGNED TINYINT, SET FOREIGN KEY
    player_id INT UNSIGNED NOT NULL, -- USING UNSIGNED INT
    goal_id INT UNSIGNED PRIMARY KEY, -- USING UNSIGNED INT, SET PK
    goal_time CHAR(10) NOT NULL -- USING UNSIGNED INT
);

CREATE TABLE FOUL_OF(
	match_id INT UNSIGNED NOT NULL, -- USING UNSIGNED INT, SET FOREIGN KEY
    club_id INT UNSIGNED NOT NULL, -- USING UNSIGNED TINYINT, SET FOREIGN KEY
    player_id INT UNSIGNED NOT NULL, -- USING UNSIGNED INT
    foul_time CHAR(10) NOT NULL, -- USING UNSIGNED TINYINT
    sent_off BOOLEAN NOT NULL -- USING BOOLEAN
);
-- END OF CODE --
-- Didn't contain foreign key